# Generated by Django 2.1 on 2018-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('student_phone_no', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(max_length=500)),
                ('sem', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth'), ('5', 'Fifth'), ('6', 'Sixth'), ('7', 'Seventh'), ('8', 'Eighth')], max_length=10)),
                ('email_id', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
