# Generated by Django 2.1 on 2018-09-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0003_glueblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='glueblog',
            name='resource_link',
            field=models.URLField(null=True),
        ),
    ]
