# Generated by Django 2.1 on 2018-08-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ug_program', models.CharField(choices=[('CS', 'COMPUTER SCIENCE & ENGG'), ('ENC', 'ELECTRONICS AND COMMUNICATION & ENGG'), ('CV', 'CIVIL ENGG'), ('ME', 'MECHANICAL ENGG')], max_length=40)),
                ('student_phone_no', models.CharField(max_length=10)),
                ('parents_phone_no', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
