# Generated by Django 2.1 on 2018-08-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180819_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(choices=[('CS', 'COMPUTER SCIENCE & ENGG'), ('ENC', 'ELECTRONICS AND COMMUNICATION & ENGG'), ('CV', 'CIVIL ENGG'), ('ME', 'MECHANICAL ENGG'), ('GECH', 'COLLEGE')], max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
