# Generated by Django 2.1 on 2018-08-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180823_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='department',
            name='students',
        ),
    ]
