# Generated by Django 2.1 on 2018-08-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180823_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Department'),
        ),
    ]
