# Generated by Django 2.1 on 2018-09-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180825_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
                ('phone_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('CS', 'COMPUTER SCIENCE & ENGG'), ('ENC', 'ELECTRONICS AND COMMUNICATION & ENGG'), ('CV', 'CIVIL ENGG'), ('IS', 'INFORMATION SCIENCE')], max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Department'),
        ),
    ]
