# Generated by Django 2.1 on 2018-09-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180912_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='department_id',
            new_name='department',
        ),
    ]
